//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ctor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ctor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find area in frame {0} at point ({1}, {2})..
        /// </summary>
        public static string CannotFindAreaInFrame {
            get {
                return ResourceManager.GetString("CannotFindAreaInFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find area in position at point ({0}, {1})..
        /// </summary>
        public static string CannotFindAreaInPosition {
            get {
                return ResourceManager.GetString("CannotFindAreaInPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find fittings type for given parameters..
        /// </summary>
        public static string CannotFindFittingsType {
            get {
                return ResourceManager.GetString("CannotFindFittingsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert false mullion..
        /// </summary>
        public static string CannotInsertFalseMullion {
            get {
                return ResourceManager.GetString("CannotInsertFalseMullion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert frame..
        /// </summary>
        public static string CannotInsertFrame {
            get {
                return ResourceManager.GetString("CannotInsertFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert sash..
        /// </summary>
        public static string CannotInsertSash {
            get {
                return ResourceManager.GetString("CannotInsertSash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert fittings.
        /// </summary>
        public static string InsertFittings {
            get {
                return ResourceManager.GetString("InsertFittings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This area has been invalidated..
        /// </summary>
        public static string InvalidArea {
            get {
                return ResourceManager.GetString("InvalidArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame does not contain empty area..
        /// </summary>
        public static string NoEmptyAreaInFrame {
            get {
                return ResourceManager.GetString("NoEmptyAreaInFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position does not contain empty area..
        /// </summary>
        public static string NoEmptyAreaInPosition {
            get {
                return ResourceManager.GetString("NoEmptyAreaInPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fittings group with ID = {0}..
        /// </summary>
        public static string NoFittingsGroupWithID {
            get {
                return ResourceManager.GetString("NoFittingsGroupWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position does not contain frame {0}..
        /// </summary>
        public static string NoFrameInPosition {
            get {
                return ResourceManager.GetString("NoFrameInPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame {0} does not contain sash {1}..
        /// </summary>
        public static string NoSashInFrame {
            get {
                return ResourceManager.GetString("NoSashInFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This position doesn&apos;t have top object..
        /// </summary>
        public static string NoTopObject {
            get {
                return ResourceManager.GetString("NoTopObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sash is not standard and therefore cannot be set as tilt-only..
        /// </summary>
        public static string NotStandardSash {
            get {
                return ResourceManager.GetString("NotStandardSash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No window type with ID = {0}..
        /// </summary>
        public static string NoWindowTypeWithID {
            get {
                return ResourceManager.GetString("NoWindowTypeWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select fittings group.
        /// </summary>
        public static string SelectFittingsGroup {
            get {
                return ResourceManager.GetString("SelectFittingsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select fittings group and repeat it again..
        /// </summary>
        public static string SelectFittingsGroupFirst {
            get {
                return ResourceManager.GetString("SelectFittingsGroupFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select glasspacket.
        /// </summary>
        public static string SelectGlasspacket {
            get {
                return ResourceManager.GetString("SelectGlasspacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select glasspacket first and repeat it again..
        /// </summary>
        public static string SelectGlasspacketFirst {
            get {
                return ResourceManager.GetString("SelectGlasspacketFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select window color.
        /// </summary>
        public static string SelectWindowColor {
            get {
                return ResourceManager.GetString("SelectWindowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select window color first and repeat it again..
        /// </summary>
        public static string SelectWindowColorFirst {
            get {
                return ResourceManager.GetString("SelectWindowColorFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select window type.
        /// </summary>
        public static string SelectWindowType {
            get {
                return ResourceManager.GetString("SelectWindowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select window type first and repeat it again..
        /// </summary>
        public static string SelectWindowTypeFirst {
            get {
                return ResourceManager.GetString("SelectWindowTypeFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default fittings group.
        /// </summary>
        public static string UseDefaultFittingsGroup {
            get {
                return ResourceManager.GetString("UseDefaultFittingsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default glasspacket.
        /// </summary>
        public static string UseDefaultGlasspacket {
            get {
                return ResourceManager.GetString("UseDefaultGlasspacket", resourceCulture);
            }
        }
    }
}
